trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Hello
  jobs:
  - job: SayHello
    steps:
    - script: echo 'Hello World'
    - script: echo 'im Sunidhi'
    - script: echo 'blahhh'
    - script: echo 'zzzzzzzzzz'

